
#ifndef CHECO_FOREGROUND_APP_TRACKER_EXPORT_H
#define CHECO_FOREGROUND_APP_TRACKER_EXPORT_H

#ifdef CHECO_FOREGROUND_APP_TRACKER_STATIC_DEFINE
#  define CHECO_FOREGROUND_APP_TRACKER_EXPORT
#  define CHECO_FOREGROUND_APP_TRACKER_NO_EXPORT
#else
#  ifndef CHECO_FOREGROUND_APP_TRACKER_EXPORT
#    ifdef checo_foreground_app_tracker_EXPORTS
        /* We are building this library */
#      define CHECO_FOREGROUND_APP_TRACKER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CHECO_FOREGROUND_APP_TRACKER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CHECO_FOREGROUND_APP_TRACKER_NO_EXPORT
#    define CHECO_FOREGROUND_APP_TRACKER_NO_EXPORT 
#  endif
#endif

#ifndef CHECO_FOREGROUND_APP_TRACKER_DEPRECATED
#  define CHECO_FOREGROUND_APP_TRACKER_DEPRECATED __declspec(deprecated)
#endif

#ifndef CHECO_FOREGROUND_APP_TRACKER_DEPRECATED_EXPORT
#  define CHECO_FOREGROUND_APP_TRACKER_DEPRECATED_EXPORT CHECO_FOREGROUND_APP_TRACKER_EXPORT CHECO_FOREGROUND_APP_TRACKER_DEPRECATED
#endif

#ifndef CHECO_FOREGROUND_APP_TRACKER_DEPRECATED_NO_EXPORT
#  define CHECO_FOREGROUND_APP_TRACKER_DEPRECATED_NO_EXPORT CHECO_FOREGROUND_APP_TRACKER_NO_EXPORT CHECO_FOREGROUND_APP_TRACKER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef CHECO_FOREGROUND_APP_TRACKER_NO_DEPRECATED
#    define CHECO_FOREGROUND_APP_TRACKER_NO_DEPRECATED
#  endif
#endif

#endif /* CHECO_FOREGROUND_APP_TRACKER_EXPORT_H */
