
#ifndef CHECO_COMMAND_EXECUTOR_EXPORT_H
#define CHECO_COMMAND_EXECUTOR_EXPORT_H

#ifdef CHECO_COMMAND_EXECUTOR_STATIC_DEFINE
#  define CHECO_COMMAND_EXECUTOR_EXPORT
#  define CHECO_COMMAND_EXECUTOR_NO_EXPORT
#else
#  ifndef CHECO_COMMAND_EXECUTOR_EXPORT
#    ifdef checo_command_executor_EXPORTS
        /* We are building this library */
#      define CHECO_COMMAND_EXECUTOR_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CHECO_COMMAND_EXECUTOR_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CHECO_COMMAND_EXECUTOR_NO_EXPORT
#    define CHECO_COMMAND_EXECUTOR_NO_EXPORT 
#  endif
#endif

#ifndef CHECO_COMMAND_EXECUTOR_DEPRECATED
#  define CHECO_COMMAND_EXECUTOR_DEPRECATED __declspec(deprecated)
#endif

#ifndef CHECO_COMMAND_EXECUTOR_DEPRECATED_EXPORT
#  define CHECO_COMMAND_EXECUTOR_DEPRECATED_EXPORT CHECO_COMMAND_EXECUTOR_EXPORT CHECO_COMMAND_EXECUTOR_DEPRECATED
#endif

#ifndef CHECO_COMMAND_EXECUTOR_DEPRECATED_NO_EXPORT
#  define CHECO_COMMAND_EXECUTOR_DEPRECATED_NO_EXPORT CHECO_COMMAND_EXECUTOR_NO_EXPORT CHECO_COMMAND_EXECUTOR_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef CHECO_COMMAND_EXECUTOR_NO_DEPRECATED
#    define CHECO_COMMAND_EXECUTOR_NO_DEPRECATED
#  endif
#endif

#endif /* CHECO_COMMAND_EXECUTOR_EXPORT_H */
